# ------------------------
# Directory where all the data files are relative to this script.
data.path <- "data"
WQFreshEstuaryData.file <- file.path(data.path,"WaterQualityFreshEstuaryData.csv")
WQGuidelines.file <- file.path(data.path,"WaterQualityGuidelines.csv")

# Location of where all the files generated by this script are saved. These files 
# are not saved to the Git code repository. (excluded in the .gitignore)
outputs.path <- file.path("output")

# -------------------------------------------------------------------
#Functions
# -------------------------------------------------------------------
standardisedScoreToGrade <- function(score) {
  grade <- ifelse (score>=81,"A",
                   ifelse(score>=61,"B",
                          ifelse(score>=41,"C",
                                 ifelse(score>=21,"D",
                                        "E"))))
  return(grade)
  
}

# -------------------------------------------------------------------
# Start of main code
# -------------------------------------------------------------------

# ------------------------
# Test if dplyr is already installed. If not then try to install it.
if("dplyr" %in% rownames(installed.packages()) == FALSE) {
  print("dplyr library is not installed on this machine. Attempting to install.")
  install.packages("dplyr")
  stop("Rerun the script once dplyr installation is complete.")
} else {
  print("Required dplyr is installed.")
}
library(dplyr)

#this means if outputs folder does not exist, create one
if (!dir.exists(outputs.path)) {
  dir.create(outputs.path, showWarnings = TRUE)
  print(paste("Created output directory: ",outputs.path))
}

# -------------------------------------
# Read in the data and guidelines
print("Attempting to load input water quality data")
if (!file.exists(WQFreshEstuaryData.file)) {
  print(paste("Could not find ",WQFreshEstuaryData.file))
  stop("Ensure that your data is saved in CSV format and is saved to the correct location")
} 

WQFreshEstuaryData <- read.csv(WQFreshEstuaryData.file, header=TRUE, sep=",", stringsAsFactors=FALSE)
print(paste("Loading successful. Found",nrow(WQFreshEstuaryData),"rows of data"))


print("Attempting to load input water quality guidelines table file")
if (!file.exists(WQGuidelines.file)) {
  print(paste("Could not find ",WQGuidelines.file))
  stop("Ensure that your Water Quality Guidelines file is saved in CSV format and is saved to the correct location")
}
WQGuidelines <- read.csv(WQGuidelines.file, header=TRUE, sep=",", stringsAsFactors=FALSE)
print(paste("Loading successful. Found",nrow(WQGuidelines),"rows of data"))

# ---------------------------------
# Add on DIN
# ---------------------------------
WQFreshEstuaryData$DIN <- WQFreshEstuaryData$Nox+WQFreshEstuaryData$Ammonia

# --------------------------------------------------------------------------------------
# Calculating the median for each month for each site
# --------------------------------------------------------------------------------------

WQFreshEstuaryData.monthlymedian <- WQFreshEstuaryData %>% group_by(Site, Month) %>% 
  summarise_at(vars(Turbidity, Phosphorus, DO, DIN), function(x) median(x, na.rm=TRUE)) 

# --------------------------------------------------------------------------------------
# Calculate the annual median of the monthly medians
# --------------------------------------------------------------------------------------
WQFreshEstuaryData.annualmedian <- WQFreshEstuaryData.monthlymedian %>% 
  group_by(Site) %>% 
  summarise_at(vars(Turbidity, Phosphorus, DO, DIN), function(x) median(x, na.rm=TRUE)) 

# Number of median values ≤ to the guideline values
