# ------------------------
# Directory where all the data files are relative to this script.
data.path <- "data"
WQFreshEstuaryData.file <- file.path(data.path,"WaterQualityFreshEstuaryData201819.csv")
WQGuidelines.file <- file.path(data.path,"WaterQualityGuidelines.csv")

# Location of where all the files generated by this script are saved. These files 
# are not saved to the Git code repository. (excluded in the .gitignore)
outputs.path <- file.path("output")

# -------------------------------------------------------------------
#Functions
# -------------------------------------------------------------------
standardisedScoreToGrade <- function(score) {
  grade <- ifelse (score>=81,"A",
                   ifelse(score>=61,"B",
                          ifelse(score>=41,"C",
                                 ifelse(score>=21,"D",
                                        "E"))))
  return(grade)
  
}

# -------------------------------------------------------------------
# Start of main code
# -------------------------------------------------------------------

# ------------------------
# Test if dplyr is already installed. If not then try to install it.
if("tidyr" %in% rownames(installed.packages()) == FALSE) {
  print("tidyr library is not installed on this machine. Attempting to install.")
  install.packages("tidyr")
  stop("Rerun the script once tidyr installation is complete.")
} else {
  print("Required tidyr is installed.")
}

library(dplyr)
library(lubridate)

#this means if outputs folder does not exist, create one
if (!dir.exists(outputs.path)) {
  dir.create(outputs.path, showWarnings = TRUE)
  print(paste("Created output directory: ",outputs.path))
}

# -------------------------------------
# Read in the data and guidelines
print("Attempting to load input water quality data")
if (!file.exists(WQFreshEstuaryData.file)) {
  print(paste("Could not find ",WQFreshEstuaryData.file))
  stop("Ensure that your data is saved in CSV format and is saved to the correct location")
} 

WQFreshEstuaryData <- read.csv(WQFreshEstuaryData.file, header=TRUE, sep=",", stringsAsFactors=FALSE)
print(paste("Loading successful. Found",nrow(WQFreshEstuaryData),"rows of data"))


print("Attempting to load input water quality guidelines table file")
if (!file.exists(WQGuidelines.file)) {
  print(paste("Could not find ",WQGuidelines.file))
  stop("Ensure that your Water Quality Guidelines file is saved in CSV format and is saved to the correct location")
}
WQGuidelines <- read.csv(WQGuidelines.file, header=TRUE, sep=",", stringsAsFactors=FALSE)
print(paste("Loading successful. Found",nrow(WQGuidelines),"rows of data"))

# ---------------------------------
# Add on DIN
# ---------------------------------
WQFreshEstuaryData$DIN <- WQFreshEstuaryData$Nox+WQFreshEstuaryData$Ammonia
WQFreshEstuaryData$Month <- format(dmy(WQFreshEstuaryData$Date),"%B")

# --------------------------------------------------------------------------------------
# Calculating the median for each month for each site
# --------------------------------------------------------------------------------------

WQFreshEstuaryData.monthlymedian <- WQFreshEstuaryData %>% group_by(Site, Month) %>% 
  summarise_at(vars(Turbidity, TP, FRP, DO, DIN, TSS, Chlorophyll), function(x) median(x, na.rm=TRUE)) 

# --------------------------------------------------------------------------------------
# Calculate the annual median of the monthly medians

#this code means group the data by site and then summarise by variables Turbidity, Phosphorus etc and then on each of these variables calculate the median
#Mackay-whitsunday and Wet Tropics report on TSS and Chlorophyll a so this needs to be included as well

# --------------------------------------------------------------------------------------
WQFreshEstuaryData.annualmedian <- WQFreshEstuaryData.monthlymedian %>% 
  group_by(Site) %>% 
  summarise_at(vars(Turbidity, TP, FRP, DO, DIN, TSS, Chlorophyll), function(x) median(x, na.rm=TRUE)) 


# -----------------------------------------------------------
# Convert the WQGuidelines from long to wide format
# -----------------------------------------------------------

# Expand the seasons to have months
seasons <- data.frame(
  Month=c('October','November','December','January','February','March',
          'April','May','June','July','August','September'),
  Season=c(rep("Wet",6),rep("Dry",6)))
WQGuidelines.allmonths <- merge(WQGuidelines.wide,seasons)
WQGuidelines.allmonths <- rename(WQGuidelines.allmonths, Turbidity.WQO=Turbidity,Chlorophyll.WQO=Chlorophyll,DIN.WQO=DIN,FRP.WQO=FRP,TSS.WQO=TSS,TP.WQO=TP)

# Attach all the matching guideline values (by month and site)
WQFreshEstuaryData.GV <- merge(WQFreshEstuaryData.monthlymedian,WQGuidelines.allmonths)


#Calculatinng the percent of months below GVs - generic function
belowGVFreq <- function(x,measure,WQO) {
#x <- WQFreshEstuaryData.GV
#measure <- "Turbidity"
#WQO <- "Turbidity.WQO"
  x$belowGV <- x[,measure]<x[,WQO]
  monthsBelowGV.site <- x %>% group_by(Site) %>% summarise_at(vars(belowGV), sum)
  numMonths.site <- x %>% group_by(Site) %>% summarise_at(vars(belowGV), length)
  #monthsBelowGV.site$belowGV/numMonths.site
  monthsBelowGV.site$fracBelowGV <- monthsBelowGV.site$belowGV/numMonths.site$belowGV
  return(monthsBelowGV.site)
}

#This is applying the function for Turbidity
turbidity.belowGVFreq <- belowGVFreq(WQFreshEstuaryData.GV,"Turbidity","Turbidity.WQO")





# Number of median monthly values below ≤ the guideline values
#WQFreshEstuaryData.MediansBelowGVs<-WQFreshEstuaryData.monthlymedian%>%
#  group_by(Site) %>% 
#  summarise_at(vars(Turbidity, TP, FRP, DO, DIN, TSS, Chlorophyll), function(x) sum(x<=   , na.rm=TRUE)) 
#WQFreshEstuaryData.MediansBelowGVs

#NEED TO WORK OUT HOW TO PUT IN THE GUIDELINE VALUES IN EACH OF THE ABOVE













#Length of each variable data column
#WQFreshEstuaryData.Lengthmonthlymedian<-WQFreshEstuaryData.monthlymedian%>%(summarise_each(funs(length))

#Percent of median values ≤ GV - calculated by number of median monthly values below GV divided by number of monthly values
#WQFreshEstuaryData.PercentBelowGVs<-WQFreshEstuaryData.MediansBelowGVs/



#This is calculating the 80th percentile for each variable
#WQFreshEstuaryData.monthlymedian %>% group_by(Site) %>% summarise_at(vars(Turbidity, TP, FRP, DO, DIN, TSS, Chlorophyll), function(WQFreshEstuaryData.monthlymedian) (quantile(WQFreshEstuaryData.monthlymedian, prob=c(0.8),na.rm=TRUE)))








